[model_providers.openrouter]
name = "OpenRouter"
base_url = "https://openrouter.ai/api/v1"
env_key = "OPENROUTER_API_KEY"

# Set OpenRouter as default provider
provider = "openrouter"
model = "microsoft/wizardlm-2-8x22b"